CREATE TABLE "tenant_role_permissions" (
  "id"         uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  "tenant_id"  uuid        NOT NULL REFERENCES "tenants"("id") ON DELETE CASCADE,
  "role"       "tenant_role" NOT NULL,
  "resource"   varchar(64) NOT NULL,
  "action"     varchar(64) NOT NULL,
  "allowed"    boolean     NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL DEFAULT now()
);--> statement-breakpoint
CREATE UNIQUE INDEX "trp_uniq"       ON "tenant_role_permissions" ("tenant_id","role","resource","action");--> statement-breakpoint
CREATE        INDEX "trp_tenant_idx" ON "tenant_role_permissions" ("tenant_id");--> statement-breakpoint

-- Seed defaults for all existing tenants
INSERT INTO "tenant_role_permissions" ("tenant_id","role","resource","action","allowed")
SELECT t.id, d.role::tenant_role, d.resource, d.action, d.allowed
FROM "tenants" t
CROSS JOIN (VALUES
  ('tenant_admin','users','view',   true),
  ('tenant_admin','users','invite', true),
  ('tenant_admin','users','edit',   true),
  ('tenant_admin','users','delete', true),
  ('tenant_admin','tutors','view',   true),
  ('tenant_admin','tutors','invite', true),
  ('tenant_admin','tutors','edit',   true),
  ('tenant_admin','tutors','delete', true),
  ('tenant_admin','students','view',   true),
  ('tenant_admin','students','invite', true),
  ('tenant_admin','students','edit',   true),
  ('tenant_admin','students','delete', true),
  ('tenant_admin','courses','view',   true),
  ('tenant_admin','courses','create', true),
  ('tenant_admin','courses','edit',   true),
  ('tenant_admin','courses','delete', true),
  ('tenant_admin','batches','view',   true),
  ('tenant_admin','batches','create', true),
  ('tenant_admin','batches','edit',   true),
  ('tenant_admin','batches','delete', true),
  ('tenant_admin','batches','enroll', true),
  ('finance_admin','users','view',    true),
  ('finance_admin','users','invite',  false),
  ('finance_admin','users','edit',    false),
  ('finance_admin','users','delete',  false),
  ('finance_admin','tutors','view',   true),
  ('finance_admin','tutors','invite', false),
  ('finance_admin','tutors','edit',   false),
  ('finance_admin','tutors','delete', false),
  ('finance_admin','students','view',   true),
  ('finance_admin','students','invite', false),
  ('finance_admin','students','edit',   false),
  ('finance_admin','students','delete', false),
  ('finance_admin','courses','view',   true),
  ('finance_admin','courses','create', false),
  ('finance_admin','courses','edit',   false),
  ('finance_admin','courses','delete', false),
  ('finance_admin','batches','view',   true),
  ('finance_admin','batches','create', false),
  ('finance_admin','batches','edit',   false),
  ('finance_admin','batches','delete', false),
  ('finance_admin','batches','enroll', false),
  ('tutor','users','view',    false),
  ('tutor','users','invite',  false),
  ('tutor','users','edit',    false),
  ('tutor','users','delete',  false),
  ('tutor','tutors','view',   true),
  ('tutor','tutors','invite', false),
  ('tutor','tutors','edit',   false),
  ('tutor','tutors','delete', false),
  ('tutor','students','view',   true),
  ('tutor','students','invite', true),
  ('tutor','students','edit',   false),
  ('tutor','students','delete', false),
  ('tutor','courses','view',   true),
  ('tutor','courses','create', true),
  ('tutor','courses','edit',   true),
  ('tutor','courses','delete', false),
  ('tutor','batches','view',   true),
  ('tutor','batches','create', true),
  ('tutor','batches','edit',   true),
  ('tutor','batches','delete', false),
  ('tutor','batches','enroll', true),
  ('student','users','view',    false),
  ('student','users','invite',  false),
  ('student','users','edit',    false),
  ('student','users','delete',  false),
  ('student','tutors','view',   false),
  ('student','tutors','invite', false),
  ('student','tutors','edit',   false),
  ('student','tutors','delete', false),
  ('student','students','view',   false),
  ('student','students','invite', false),
  ('student','students','edit',   false),
  ('student','students','delete', false),
  ('student','courses','view',   true),
  ('student','courses','create', false),
  ('student','courses','edit',   false),
  ('student','courses','delete', false),
  ('student','batches','view',   true),
  ('student','batches','create', false),
  ('student','batches','edit',   false),
  ('student','batches','delete', false),
  ('student','batches','enroll', true)
) AS d(role, resource, action, allowed)
ON CONFLICT DO NOTHING;
